---
apiVersion: v1
kind: Service
metadata:
  annotations:
    softwareos-base/audit-log-level: minimal
    softwareos-base/governance-policy: standard-v1
    softwareos-base/uri: softwareos-base://k8s/platform-observops/service/observops-engine
    softwareos-base/urn: urn:softwareos-base:k8s:platform-observops:service:observops-engine:sha256-8118fc0d741c1dd884adc538319482decc26ba18a5287795a4e7fa549cdb9de1
  labels:
    app.kubernetes.io/component: engine
    app.kubernetes.io/instance: observops-engine-prod
    app.kubernetes.io/name: observops-engine
    app.kubernetes.io/part-of: softwareos-base
    app.kubernetes.io/version: 1.0.0
    softwareos-base/environment: production
    softwareos-base/owner: eco-system
    softwareos-base/platform: platform-observops
    governance.io/managed: 'true'
  name: observops-engine
  namespace: eco-observops
spec:
  ports:
  - name: http
    port: 8094
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 9094
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/component: engine
    app.kubernetes.io/name: observops-engine
  type: ClusterIP
