apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eco.fullname" . }}
  namespace: {{ .Values.namespace | default "softwareos-base" }}
  labels:
  {{- include "eco.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: "softwareos-base-sa@softwareos-base.iam.gserviceaccount.com"
automountServiceAccountToken: true
