---
apiVersion: v1
data:
  SECCOMPOPS_AUDIT_MODE: continuous
  SECCOMPOPS_DB_HOST: seccompops-postgres
  SECCOMPOPS_DB_NAME: seccompops
  SECCOMPOPS_DB_PORT: '5432'
  SECCOMPOPS_ENFORCEMENT_MODE: strict
  SECCOMPOPS_ENV: production
  SECCOMPOPS_LOG_FORMAT: json
  SECCOMPOPS_LOG_LEVEL: INFO
  SECCOMPOPS_PLATFORM_SECCOMPOPS_REDIS_URL: redis://seccompops-redis:6379/0
kind: ConfigMap
metadata:
  annotations:
    softwareos-base/audit-log-level: minimal
    softwareos-base/governance-policy: standard-v1
    softwareos-base/uri: softwareos-base://k8s/core/configmap/seccompops-config
    softwareos-base/urn: urn:softwareos-base:k8s:core:configmap:seccompops-config:sha256-2be986c5dcf490ee0cf83206b6b9e42b67f0346ffb797f57980230ca2a65b93a
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: seccompops-platform
    app.kubernetes.io/part-of: softwareos-base
    app.kubernetes.io/version: 1.0.0
    softwareos-base/environment: development
    softwareos-base/owner: eco-system
    softwareos-base/platform: core
    governance.io/managed: 'true'
  name: seccompops-config
  namespace: eco-seccompops
