---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    softwareos-base/audit-log-level: minimal
    softwareos-base/governance-policy: standard-v1
    softwareos-base/uri: softwareos-base://k8s/core/secret/quantumflow-secrets
    softwareos-base/urn: urn:softwareos-base:k8s:core:secret:quantumflow-secrets:sha256-5672715ebb9ea9a850a6636b2ba5e4cc37d1c964d110e34a1e256e891fb0cbf2
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: quantumflow
    app.kubernetes.io/part-of: softwareos-base
    app.kubernetes.io/version: 1.0.0
    softwareos-base/environment: development
    softwareos-base/governance: aligned
    softwareos-base/owner: eco-system
    softwareos-base/part-of: softwareos-base
    softwareos-base/platform: core
  name: quantumflow-secrets
  namespace: quantumflow
stringData:
  ALLOWED_ORIGINS: http://localhost:3000,https://yourdomain.com
  SECRET_KEY: change-me-in-production-use-strong-random-key
type: Opaque
