---
apiVersion: v1
data:
  CIRCLECI_RUNNER_MODE: single-task
  CIRCLECI_RUNNER_NAME: softwareos-base-gke-runner
  CIRCLECI_RUNNER_RESOURCE_CLASS: eco/base
  CLEANUP_WORKSPACE: 'true'
  LOG_FORMAT: json
  LOG_LEVEL: info
  POD_CHECK_INTERVAL: 30s
  POD_TIMEOUT: 10m
  WORKING_DIRECTORY: /tmp/circleci-workspace
kind: ConfigMap
metadata:
  annotations:
    softwareos-base/audit-log-level: minimal
    softwareos-base/governance-policy: standard-v1
    softwareos-base/uri: softwareos-base://k8s/core/configmap/circleci-agent-config
    softwareos-base/urn: urn:softwareos-base:k8s:core:configmap:circleci-agent-config:sha256-21a44144da79099d2158e98d693d2b3e4f2fddf27d493c95aacfde800b450fce
  labels:
    app: circleci-runner
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: circleci-agent-config
    app.kubernetes.io/part-of: softwareos-base
    app.kubernetes.io/version: 1.0.0
    softwareos-base/environment: development
    softwareos-base/owner: eco-system
    softwareos-base/platform: core
  name: circleci-agent-config
  namespace: circleci-runner
