#!/bin/bash
set -euo pipefail

# Bootstrap Script - Initialize Development Environment
# Creates necessary directories, checks dependencies, and generates initial index

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Audit logging
audit_log() {
    local action="$1"
    local resource="$2"
    local result="$3"
    local hash_value="${4:-}"
    
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local request_id=$(python3 -c "import uuid; print(uuid.uuid4())" 2>/dev/null || echo "unknown")
    local correlation_id=$(python3 -c "import uuid; print(uuid.uuid4())" 2>/dev/null || echo "unknown")
    
    local log_entry=$(cat <<EOF
{
  "timestamp": "${timestamp}",
  "actor": "bootstrap",
  "action": "${action}",
  "resource": "${resource}",
  "result": "${result}",
  "hash": "${hash_value}",
  "version": "1.0.0",
  "requestId": "${request_id}",
  "correlationId": "${correlation_id}",
  "ip": "unknown",
  "userAgent": "bootstrap.sh"
}
EOF
)
    
    local audit_dir="${ROOT_DIR}/audit"
    mkdir -p "${audit_dir}"
    local audit_file="${audit_dir}/bootstrap_$(date -u +"%Y%m%d").jsonl"
    echo "${log_entry}" >> "${audit_file}"
}

echo -e "${GREEN}[bootstrap] Starting initialization...${NC}"

# Step 1: Create directory structure
echo "[bootstrap] Creating directory structure..."
mkdir -p "${ROOT_DIR}/architecture"
mkdir -p "${ROOT_DIR}/schemas"
mkdir -p "${ROOT_DIR}/policies"
mkdir -p "${ROOT_DIR}/governance"
mkdir -p "${ROOT_DIR}/audit"
mkdir -p "${ROOT_DIR}/artifacts"
mkdir -p "${ROOT_DIR}/snapshots"
mkdir -p "${ROOT_DIR}/.config"
mkdir -p "${ROOT_DIR}/logs"
mkdir -p "${ROOT_DIR}/deploy"
mkdir -p "${ROOT_DIR}/tests"

audit_log "create_directories" "directory_structure" "success" ""

# Step 2: Check prerequisites
echo "[bootstrap] Checking prerequisites..."

check_command() {
    local cmd="$1"
    if command -v "${cmd}" &> /dev/null; then
        echo -e "  ${GREEN}✓${NC} ${cmd}"
        return 0
    else
        echo -e "  ${YELLOW}✗${NC} ${cmd} (not found)"
        return 1
    fi
}

MISSING_DEPS=0
check_command "node" || MISSING_DEPS=$((MISSING_DEPS + 1))
check_command "python3" || MISSING_DEPS=$((MISSING_DEPS + 1))
check_command "git" || MISSING_DEPS=$((MISSING_DEPS + 1))
check_command "docker" || MISSING_DEPS=$((MISSING_DEPS + 1))

if [[ ${MISSING_DEPS} -gt 0 ]]; then
    echo -e "${YELLOW}[bootstrap] Warning: ${MISSING_DEPS} prerequisite(s) missing${NC}"
    echo "[bootstrap] Run: ./scripts/install-deps.sh to install missing dependencies"
    audit_log "check_prerequisites" "dependencies" "partial" ""
else
    echo -e "${GREEN}[bootstrap] All prerequisites satisfied${NC}"
    audit_log "check_prerequisites" "dependencies" "success" ""
fi

# Step 3: Install Python dependencies
echo "[bootstrap] Installing Python dependencies..."
if pip3 install pyyaml &> /dev/null; then
    echo -e "  ${GREEN}✓${NC} pyyaml"
    audit_log "install_deps" "pyyaml" "success" ""
else
    echo -e "  ${YELLOW}✗${NC} pyyaml (failed)"
    audit_log "install_deps" "pyyaml" "failure" ""
fi

# Step 4: Generate root index
echo "[bootstrap] Generating root index..."
if [[ -f "${ROOT_DIR}/scripts/rot_indexer.py" ]]; then
    cd "${ROOT_DIR}"
    if python3 scripts/rot_indexer.py; then
        echo -e "  ${GREEN}✓${NC} root-index.json generated"
        audit_log "generate_index" "architecture/root-index.json" "success" ""
    else
        echo -e "  ${YELLOW}✗${NC} root-index.json generation failed"
        audit_log "generate_index" "architecture/root-index.json" "failure" ""
    fi
else
    echo -e "  ${YELLOW}✗${NC} rot_indexer.py not found"
    audit_log "generate_index" "architecture/root-index.json" "skipped" ""
fi

# Step 5: Set up environment
echo "[bootstrap] Setting up environment..."
if [[ ! -f "${ROOT_DIR}/.env" ]]; then
    if [[ -f "${ROOT_DIR}/.env.example" ]]; then
        cp "${ROOT_DIR}/.env.example" "${ROOT_DIR}/.env"
        echo -e "  ${GREEN}✓${NC} .env created from .env.example"
        audit_log "setup_env" ".env" "success" ""
    else
        cat > "${ROOT_DIR}/.env" <<EOF
# Environment Configuration
# Generated by bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Development
NODE_ENV=development
LOG_LEVEL=info

# GitHub (if needed)
# GITHUB_TOKEN=
EOF
        echo -e "  ${GREEN}✓${NC} .env created"
        audit_log "setup_env" ".env" "success" ""
    fi
else
    echo -e "  ${YELLOW}✓${NC} .env already exists"
    audit_log "setup_env" ".env" "skipped" ""
fi

# Step 6: Initialize git hooks
echo "[bootstrap] Initializing git hooks..."
if [[ -d "${ROOT_DIR}/.git" ]]; then
    mkdir -p "${ROOT_DIR}/.git/hooks"
    
    # Pre-commit hook
    cat > "${ROOT_DIR}/.git/hooks/pre-commit" <<'EOF'
#!/bin/bash
# Pre-commit hook: Run RoT gate
set -e
cd "$(git rev-parse --show-toplevel)"
if [[ -f "scripts/rot_gate.sh" ]]; then
    ./scripts/rot_gate.sh || true
fi
EOF
    chmod +x "${ROOT_DIR}/.git/hooks/pre-commit"
    echo -e "  ${GREEN}✓${NC} pre-commit hook installed"
    audit_log "init_hooks" "pre-commit" "success" ""
else
    echo -e "  ${YELLOW}✗${NC} Not a git repository"
    audit_log "init_hooks" "pre-commit" "skipped" ""
fi

# Step 7: Verify installation
echo "[bootstrap] Verifying installation..."
VERIFICATION_PASSED=true

if [[ -f "${ROOT_DIR}/architecture/root-index.json" ]]; then
    echo -e "  ${GREEN}✓${NC} root-index.json exists"
else
    echo -e "  ${RED}✗${NC} root-index.json missing"
    VERIFICATION_PASSED=false
fi

if [[ -d "${ROOT_DIR}/audit" ]]; then
    echo -e "  ${GREEN}✓${NC} audit directory exists"
else
    echo -e "  ${RED}✗${NC} audit directory missing"
    VERIFICATION_PASSED=false
fi

if [[ "${VERIFICATION_PASSED}" = true ]]; then
    echo -e "${GREEN}[bootstrap] ✓ Verification passed${NC}"
    audit_log "verify_installation" "bootstrap" "success" ""
else
    echo -e "${YELLOW}[bootstrap] ⚠ Verification completed with warnings${NC}"
    audit_log "verify_installation" "bootstrap" "partial" ""
fi

# Step 8: Summary
echo ""
echo -e "${GREEN}[bootstrap] Initialization complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Review .env configuration"
echo "  2. Run: ./scripts/start-min.sh to start minimal services"
echo "  3. Run: ./scripts/quick-verify.sh to verify setup"
echo ""

audit_log "bootstrap_complete" "initialization" "success" ""

exit 0