#!/bin/bash
set -euo pipefail

# Fix Environment Script
# Validates and fixes .env configuration

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Audit logging
audit_log() {
    local action="$1"
    local resource="$2"
    local result="$3"
    local hash_value="${4:-}"
    
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local request_id=$(python3 -c "import uuid; print(uuid.uuid4())" 2>/dev/null || echo "unknown")
    local correlation_id=$(python3 -c "import uuid; print(uuid.uuid4())" 2>/dev/null || echo "unknown")
    
    local log_entry=$(cat <<EOF
{
  "timestamp": "${timestamp}",
  "actor": "fix-env",
  "action": "${action}",
  "resource": "${resource}",
  "result": "${result}",
  "hash": "${hash_value}",
  "version": "1.0.0",
  "requestId": "${request_id}",
  "correlationId": "${correlation_id}",
  "ip": "unknown",
  "userAgent": "fix-env.sh"
}
EOF
)
    
    local audit_dir="${ROOT_DIR}/audit"
    mkdir -p "${audit_dir}"
    local audit_file="${audit_dir}/fix-env_$(date -u +"%Y%m%d").jsonl"
    echo "${log_entry}" >> "${audit_file}"
}

echo -e "${GREEN}[fix-env] Validating and fixing environment...${NC}"
echo ""

ENV_FILE="${ROOT_DIR}/.env"
ENV_EXAMPLE="${ROOT_DIR}/.env.example"

# Check if .env exists
if [[ ! -f "${ENV_FILE}" ]]; then
    echo -e "${YELLOW}[fix-env] .env not found${NC}"
    
    if [[ -f "${ENV_EXAMPLE}" ]]; then
        echo "[fix-env] Creating .env from .env.example..."
        cp "${ENV_EXAMPLE}" "${ENV_FILE}"
        echo -e "  ${GREEN}✓${NC} .env created"
        audit_log "create_env" ".env" "success" ""
    else
        echo "[fix-env] Creating .env with defaults..."
        cat > "${ENV_FILE}" <<EOF
# Environment Configuration
# Generated by fix-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Development
NODE_ENV=development
LOG_LEVEL=info

# GitHub (if needed)
# GITHUB_TOKEN=

# API Configuration
API_PORT=8080
API_HOST=localhost

# Database (if needed)
# DATABASE_URL=

# Observability
ENABLE_METRICS=true
ENABLE_TRACING=false
EOF
        echo -e "  ${GREEN}✓${NC} .env created"
        audit_log "create_env" ".env" "success" ""
    fi
fi

# Validate required variables
echo "[fix-env] Validating required variables..."

REQUIRED_VARS=(
    "NODE_ENV"
    "LOG_LEVEL"
)

MISSING_VARS=0
for var in "${REQUIRED_VARS[@]}"; do
    if ! grep -q "^${var}=" "${ENV_FILE}"; then
        echo -e "  ${YELLOW}✗${NC} ${var} (missing)"
        MISSING_VARS=$((MISSING_VARS + 1))
        
        # Add missing variable with default
        case "${var}" in
            NODE_ENV)
                echo "NODE_ENV=development" >> "${ENV_FILE}"
                ;;
            LOG_LEVEL)
                echo "LOG_LEVEL=info" >> "${ENV_FILE}"
                ;;
        esac
        
        echo -e "    ${GREEN}+${NC} Added ${var} with default value"
        audit_log "add_var" "${var}" "success" ""
    else
        echo -e "  ${GREEN}✓${NC} ${var}"
        audit_log "validate_var" "${var}" "success" ""
    fi
done

# Validate NODE_ENV value
NODE_ENV=$(grep "^NODE_ENV=" "${ENV_FILE}" | cut -d'=' -f2)
if [[ ! "${NODE_ENV}" =~ ^(development|staging|production)$ ]]; then
    echo -e "${YELLOW}[fix-env] Warning: NODE_ENV has invalid value: ${NODE_ENV}${NC}"
    echo "[fix-env] Setting NODE_ENV to development..."
    sed -i.bak "s/^NODE_ENV=.*/NODE_ENV=development/" "${ENV_FILE}"
    rm -f "${ENV_FILE}.bak"
    audit_log "fix_var" "NODE_ENV" "success" ""
fi

# Validate LOG_LEVEL value
LOG_LEVEL=$(grep "^LOG_LEVEL=" "${ENV_FILE}" | cut -d'=' -f2)
if [[ ! "${LOG_LEVEL}" =~ ^(debug|info|warn|error)$ ]]; then
    echo -e "${YELLOW}[fix-env] Warning: LOG_LEVEL has invalid value: ${LOG_LEVEL}${NC}"
    echo "[fix-env] Setting LOG_LEVEL to info..."
    sed -i.bak "s/^LOG_LEVEL=.*/LOG_LEVEL=info/" "${ENV_FILE}"
    rm -f "${ENV_FILE}.bak"
    audit_log "fix_var" "LOG_LEVEL" "success" ""
fi

echo ""
echo -e "${GREEN}[fix-env] Environment validation complete${NC}"
echo ""
if [[ ${MISSING_VARS} -gt 0 ]]; then
    echo "Added ${MISSING_VARS} missing variable(s)"
fi
echo ""
echo "Review .env and update as needed:"
echo "  vim ${ENV_FILE}"
echo ""

audit_log "fix-env_complete" ".env" "success" ""

exit 0